---
_hotel_id: NUH877
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
latitude: 40.68891
longitude: -73.98897
name: NU Hotel Brooklyn
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 85 Smith St
  street2: ''
  state: New York
  city: Brooklyn
  country: United States
  zip_code: '11201'
